### ISSUE TITLE
The mod doesn't work for some people

### ISSUE THREAD

**Issue by Stwohm** [Koder-Teh/Boombox-Controller#1]
I used to install my mods manually without the help of the Thunderstore app and the mod was working perfectly but it didn't work for some of my friends for some reason. Then I switched to Thunderstorms because it was hard to update all of them manually, now the mod doesn't work for me and most of my friends.

**Comment by Koder-Teh** [comment]
Привет. Покажите мне логи BepInEx. Также покажите список установленных вами модификаций. Насчет мод менеджера ThunderStore, я сам им не пользуюсь. Так как мне удобно делать все вручную. Так что скорее всего, я сегодня поставлю 
мод менеджер ThunderStore, и проверю лично как с ним все работает.

**Comment by Stwohm** [comment]
[bepinex log.txt](https://github.com/Koder-Teh/Boombox-Controller/files/13762975/bepinex.log.txt)
![Screenshot_1](https://github.com/Koder-Teh/Boombox-Controller/assets/154699508/28fde543-9c11-4144-8722-69905ea2569b)
![Screenshot_2](https://github.com/Koder-Teh/Boombox-Contro
![Screenshot_3](https://github.com/Koder-Teh/Boombox-Controller/assets/154699508/3fc28ac9-5383-4bc9-b0a9-5d24d8b0ab73)
ller/assets/154699508/76315eba-978b-4055-b869-765c604e729c)
![Screenshot_4](https://github.com/Koder-Teh/Boombox-Controller/assets/154699508/dde84d10-ea4d-479d-a482-c83012c2b29d)
Sure, here are the sources you have requested.

**Comment by Koder-Teh** [comment]
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/e3b268d6-454f-4825-af56-67b3d152fe70)
У тебя не полностью загрузились дополнительные библиотеки. Зайди по пути "Lethal Company\BoomboxController\other" там увидишь zip файл, который нужно удалить.
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/4fce6ec5-4f93-4c50-afc2-6e94125a5d1a)

**Comment by Stwohm** [comment]
It worked after deleting that file! Thank you for your help, very good mod.
