### ISSUE TITLE
Having a custom yt-dlp configuration breaks downloads: "Link is invalid!"

### ISSUE THREAD

**Issue by sqwave** [Koder-Teh/Boombox-Controller#11]
I use a custom yt-dlp configuration (`%APPDATA%\yt-dlp\config.txt`) which changes the default output filename format, and that seems to break the mod. Pasting a valid youtube url in the chat results in a "Link is invalid!" error.

![image](https://github.com/Koder-Teh/Boombox-Controller/assets/155760492/e4632fc5-5269-47e4-8e3e-420699a85fb5)

When doing so, the correct video is actually downloaded inside the `BoomboxController\other` folder but the output file isn't recognized. What I did to fix was creating a `yt-dlp.conf` file with the `--ignore-config` argument inside the same folder as `yt-dlp.exe`, which seems to override the other configuration.

![image](https://github.com/Koder-Teh/Boombox-Controller/assets/155760492/dc172316-c688-48c8-9c8d-9fc29c974611)

I guess a simpler fix would be directly calling yt-dlp with `--ignore-config` inside the code.

**Comment by Koder-Teh** [comment]
Привет! Извини что я так долго тебе не отвечал. Я был занят :) Я добавил в аргументы то что ты просил. Спасибо что нашел данный баг.
