### ISSUE TITLE
Mod dont work

### ISSUE THREAD

**Issue by SaNyaZXC666** [Koder-Teh/Boombox-Controller#12]
Вот что я получаю
[Error  : Unity Log] InvalidDataException: End of Central Directory record could not be found.
Stack trace:
System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory () (at <937d55918aef4dfbb81a0589a7fa4258>:0)
System.IO.Compression.ZipArchive.Init (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen) (at <937d55918aef4dfbb81a0589a7fa4258>:0)
System.IO.Compression.ZipArchive..ctor (System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, System.Boolean leaveOpen, System.Text.Encoding entryNameEncoding) (at <937d55918aef4dfbb81a0589a7fa4258>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode, System.Text.Encoding entryNameEncoding) (at <b0823075acfb40c4808f51b1d3107552>:0)
System.IO.Compression.ZipFile.Open (System.String archiveFileName, System.IO.Compression.ZipArchiveMode mode) (at <b0823075acfb40c4808f51b1d3107552>:0)
System.IO.Compression.ZipFile.OpenRead (System.String archiveFileName) (at <b0823075acfb40c4808f51b1d3107552>:0)
BoomboxController.Plugin.Unpacking () (at <ed710c42d6cc4a0ca49c79ea0008d4db>:0)
BoomboxController.Plugin.Awake () (at <ed710c42d6cc4a0ca49c79ea0008d4db>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by Koder-Teh** [comment]
Привет, это ошибка связанно с тем что вы не до конца скачали файл zip. Который автоматически скачивается при запуске модификации.
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/19576bd2-c7ed-4ec2-af99-2075eab34b58)
Удали его, и попробуй еще раз запустить игру и подождать. Мод прекрасно работает :)

**Comment by Koder-Teh** [comment]
Привет! В новой версии мода, я добавил защиту от битых зип файлов. Спасибо что пользуешься моим модом :)
