### ISSUE TITLE
this mod breaks other chat command - mods

### ISSUE THREAD

**Issue by Toemmsen96** [Koder-Teh/Boombox-Controller#13]
Hi, i have a small request here. Could you make it so the chat doesnt get cleared and the submitting function isnt overwritten to false? This breaks any other mod that has to do with chat commands like for example mine.
These are the problematic lines of code:
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/147745097/ba8e766b-dcfe-46fb-a47d-22427b9e0eae)

You could make it so the chat still just gets submitted if you dont detect a command. This way chat commands with other prefixes for the commands can still work.

**Comment by jwidess** [comment]
Thanks for posting this @Toemmsen96 I really would love to use your ChatCommands mod with the Boombox Controller mod so hopefully @Koder-Teh gets this fixed!

**Comment by Koder-Teh** [comment]
Привет! В новой версии мода я исправил данный баг. Спасибо что написали об этой проблеме :)
