### ISSUE TITLE
Change Default color for new installation

### ISSUE THREAD

**Issue by bubin7766** [Koder-Teh/Boombox-Controller#14]
Leaving the box as the default Iconic blue instead of having to explain to users how to change it back and why the boombox is white every time would be a nice imo.
Unless there is a way to change the color for the configs that export with the modpack, it is a pain having to guide users on how to change the color with notepad

**Comment by Koder-Teh** [comment]
Привет! Извини что так долго отвечал. Я добавил то что ты просил меня, надеюсь ты будешь дальше играть с моим модом. Спасибо что написал :)
