### ISSUE TITLE
Boombox Controller config screen clips

### ISSUE THREAD

**Issue by bubin7766** [Koder-Teh/Boombox-Controller#15]
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/42780000/0809eee0-d5c6-4b52-9416-33a4e4dba80e)
As you can see Boombox Controller's config screen clips with i believe LethalCompany_InputUtils' implementation of the config screen. Would there be a way to integrate your config with theirs so it plays nicely with the menu?

**Comment by Koder-Teh** [comment]
Привет! Можешь мне скинуть логи BepInEx. Так же скинуть файл по пути: "Lethal Company\BoomboxController\logReport.txt"

**Comment by bubin7766** [comment]
Here is the report from boombox controller
[logReport.txt](https://github.com/Koder-Teh/Boombox-Controller/files/13893732/logReport.txt)
And then here is the BepInEx log
[LogOutput.log](https://github.com/Koder-Teh/Boombox-Controller/files/13893745/LogOutput.log)
Sorry I have a lot of mods installed but i do my best to make sure they're all compatible with each other

**Comment by bubin7766** [comment]
Out of curiosity does having this mod installed disable the default boombox music?
I no longer have any audio from default tracks in my boombox with your mod installed and [Boombox Sync Fix](https://thunderstore.io/c/lethal-company/p/FutureSavior/Boombox_Sync_Fix/) not sure if this mod is needed with yours though

**Comment by Koder-Teh** [comment]
> LogOutput.log

Привет! Ты используешь мод менеджер? Где BepInEx у тебя лежит? В игре его нет.

> Out of curiosity does having this mod installed disable the default boombox music?

Да.

> I no longer have any audio from default tracks in my boombox with your mod installed and [Boombox Sync Fix](https://thunderstore.io/c/lethal-company/p/FutureSavior/Boombox_Sync_Fix/) not sure if this mod is needed with yours though

Boombox Sync Не нужен в принципе. Он в целом бесполезный. Код этого "мода" не имеет смысловой нагрузки. Желательно его удалить.

**Comment by bubin7766** [comment]
> Привет ! Ты используешь мод менеджер? Где BepInEx у тебя лежит? В игре его нет.

Yes I am using r2modman to install my mods, could you point me in the right direction to find the log for you?

> Да.

Would it be possible to make that an accessible config that by default leaves the base game music on?

> Boombox Sync Не нужен в принципе. Он в целом бесполезный. Код этого "мода" не имеет смысловой нагрузки. Желательно его удалить.

Okay then thank you for letting me know! I’ll make sure to clean this up from my mod pack now

**Comment by Koder-Teh** [comment]
> Yes I am using r2modman to install my mods, could you point me in the right direction to find the log for you?

Я не знаю куда ставит BepInEx r2modman. Скорее всего должен в игру ставить. Вот моя папка с игрой:
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/ca01d70c-da2b-487c-9431-caf3d17ad9d6)

> Would it be possible to make that an accessible config that by default leaves the base game music on?

Нет, я изначально делал мод который будет брать ссылки с ютуба и другие. И загружать их в игру. Но может я сделаю такое, но мне кажется это бессмысленно.

**Comment by bubin7766** [comment]
>Я не знаю куда ставит BepInEx r2modman. Скорее всего должен в игру ставить. Вот моя папка с игрой:

Yeah my game folder doesn't look like that, I believe it looks this way since r2modman just injects the necessary files when needed while loading the game modded 
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/42780000/5743c1d8-8208-4467-87b0-0556a86575f0)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/42780000/4d588e42-d4a3-464e-aca2-ade2f1dd2f9b)


>Нет, я изначально делал мод который будет брать ссылки с ютуба и другие. И загружать их в игру. Но может я сделаю такое, но мне кажется это бессмысленно.

My reasoning for leaving the default music on would be just as a placeholder for using the boombox without typing in a link first. This also was not necessarily a request, it was just more of a curiosity since I am not sure if that would be easy to do or not

**Comment by Koder-Teh** [comment]
> ![image](https://private-user-images.githubusercontent.com/42780000/295077671-0809eee0-d5c6-4b52-9416-33a4e4dba80e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTAxMTEsIm5iZiI6MTcwNTA0OTgxMSwicGF0aCI6Ii80Mjc4MDAwMC8yOTUwNzc2NzEtMDgwOWVlZTAtZDVjNi00YjUyLTk0MTYtMzNhNGU0ZGJhODBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA4NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZmU2MWFmMDYyYmU2YWZmYWFmNWJkNGU1ZTVjNTdhNmEyNzU2OTY5NjNhZDNjNjNlMzU2NWY0MjI3ODIyYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mdxD0y344i1ty16qBZz1AC7DaPk2nbyIIeO20am5T6U) As you can see Boombox Controller's config screen clips with i believe LethalCompany_InputUtils' implementation of the config screen. Would there be a way to integrate your config with theirs so it plays nicely with the menu?

Можешь скинуть конфиг мода LethalCompany_InputUtils. 
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/4e53e6f5-40b3-4c2c-a819-5bd17d582fbf)

**Comment by Koder-Teh** [comment]
> > Я не знаю куда ставит BepInEx r2modman. Скорее всего должен в игру ставить. Вот моя папка с игрой:
> 
> Yeah my game folder doesn't look like that, I believe it looks this way since r2modman just injects the necessary files when needed while loading the game modded ![image](https://private-user-images.githubusercontent.com/42780000/295893081-5743c1d8-8208-4467-87b0-0556a86575f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTAxMTEsIm5iZiI6MTcwNTA0OTgxMSwicGF0aCI6Ii80Mjc4MDAwMC8yOTU4OTMwODEtNTc0M2MxZDgtODIwOC00NDY3LTg3YjAtMDU1NmE4NjU3NWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA4NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ODMyMGRjY2YwODlkYzQ0YmZmMWY2OWI1ZTlmZDQ3YmM2MWJhYWQ0MmM3ZjM1M2VkNDlhOTM5NGVlYThiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qEY0BslprsiN9KIf9lRJGa9jIrQYqIeibLyXmrGmvpw) ![image](https://private-user-images.githubusercontent.com/42780000/295894102-4d588e42-d4a3-464e-aca2-ade2f1dd2f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTAxMTEsIm5iZiI6MTcwNTA0OTgxMSwicGF0aCI6Ii80Mjc4MDAwMC8yOTU4OTQxMDItNGQ1ODhlNDItZDRhMy00NjRlLWFjYTItYWRlMmYxZGQyZjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA4NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MTk2ZjNmNTc4ODIzYmMyYWMyMzBhNTAyN2Y5ZGJhNTliMTRjNjFiOGQ5NDA1N2E0NzY3NjQzN2RkYWE5ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x-17_lAoWbfgtCdiGvQMGyMzyWr-A9G6CMJoY87UCQg)

Просто я не делал поддержку r2modman для мода. Но я принципе понял как он работает.

> 
> > Нет, я изначально делал мод который будет брать ссылки с ютуба и другие. И загружать их в игру. Но может я сделаю такое, но мне кажется это бессмысленно.
> 
> My reasoning for leaving the default music on would be just as a placeholder for using the boombox without typing in a link first. This also was not necessarily a request, it was just more of a curiosity since I am not sure if that would be easy to do or not

Я подумаю над этим. Мне просто нужна мотивация для этого. Энтузиазма уже потихоньку не хватает.
