### ISSUE TITLE
Issues in Main Menu and In-Game

### ISSUE THREAD

**Issue by AndrewM521** [Koder-Teh/Boombox-Controller#17]
These issue were tested in both LAN and Online with Boombox Controller as the only installed plugin on game v49.

Issue 1. When starting up Lethal Company and selecting the either option, the BepInEx CMD window gives a "Directory Not Found Exception" 
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/55631446/2374c979-6463-4d92-a290-ea5dc4823a04)
 - If I am correct, the BepInEx folder is not located in the root of the game folder

Issue 2. When doing /bplay <url> and a boombox is not spawned in the map, the CMD window will give a null object reference. 
 - Maybe trap for the missing boombox before running the commands?

Issue 3. When doing /bplay <url>, and it says "The track was uploaded to the boombox", the music does not start. The boombox UI says there is 1 available track but doing /btrack <track> does not start the song either. 
 - The only way that I was able to start a song was by pausing the CMD window. When unpausing the CMD window, the music stops. 
   - These warnings appear when unpausing 
     ![image](https://github.com/Koder-Teh/Boombox-Controller/assets/55631446/453fd298-1d9f-432a-987b-72854b5492ce)

**Comment by Koder-Teh** [comment]
> These issue were tested in both LAN and Online with Boombox Controller as the only installed plugin on game v49.

Привет! В данный момент мод поддерживается только на версии v47. Это вроде как последняя версия этой игры.
У меня игра не лицензионная, я не могу точно сказать. Но если вы дадите доступ к v49, обновлю мод до этой версии.


> Issue 1. When starting up Lethal Company and selecting the either option, the BepInEx CMD window gives a "Directory Not Found Exception"

BepInEx должен обязательно находится в папке игры. Без него мой мод и другие моды, работать не будут. Обязательно его установите.

> Issue 2. When doing /bplay and a boombox is not spawned in the map, the CMD window will give a null object reference.

Ошибку выдает потому что либо, вы не ввели ссылку в аргументы команды. Либо бумбокса нет на карте. Это в принципе логично. Исправлять ошибки буду по мере необходимости. 

> Issue 3. When doing /bplay , and it says "The track was uploaded to the boombox", the music does not start. The boombox UI says there is 1 available track but doing /btrack does not start the song either.

Скорее всего команда не работает потому что у вас нету BepInEx в папке игры. Я не знаю чем вы можете пользоваться при запуске игры. Могу предположить что мы используете мод менеджер. Но обязательно скиньте пожалуйста, логи BepInEx. Так же logReport.txt по пути: "Lethal Company\BoomboxController\logReport.txt". Обязательно решим проблему :)

> * The only way that I was able to start a song was by pausing the CMD window. When unpausing the CMD window, the music stops.

В последней версии мода я использовал WinApi. Чтобы изменить размеры консоли при выводе информации на него. Но скорее всего это не работает. И я уберу это в скором времени. Хотя у меня на пиратской игре, все работает идеально.

Спасибо за такое развернутое обращение.

**Comment by AndrewM521** [comment]
I am not using any beta versions as v49 is the latest version of the game. v47 was the latest major patch, but in the last few days it has been updated with small patches. If what google translator said was correct, you are using an unlicensed version which would make since that your current version is only v47. 

Again, these issues were tested with only Boombox Controller and BepInEx installed

For issue 1, even with BepInEx installed it still gives a "Directory Not Found" exception. This is my current Lethal Company game folder
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/55631446/ea333abd-3f34-4831-b173-c998e0e34db5)
As you can see, no BepInEx folder is present. I am using Thunderstore Mod Manager for loading the mods so I believe the .thunderstoremm file is how its loading the BepInEx folder into the game. These are my files for my current profile on Thunderstore
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/55631446/c539194a-3572-4789-9871-4b78b4af08b9)
As you can see, the BepInEx folder is present along with the plugins folder inside

For issue 3, here is the log report files
BepInEx log report: [LogOutput.log](https://github.com/Koder-Teh/Boombox-Controller/files/13906879/LogOutput.log)
Boombox Controller log report [logReport.txt](https://github.com/Koder-Teh/Boombox-Controller/files/13906886/logReport.txt)

In the BepInEx log report, the last few warnings "[Warning: Unity Log] [Dissonance:Recording] (18:06:23.219) BasicMicrophoneCapture: Insufficient buffer space, requested 90240, clamped to 16383 (dropping 73857 samples)
[Warning: Unity Log] [Dissonance:Recording] (18:06:23.220) BasePreprocessingPipeline: Lost 480 samples in the preprocessor (buffer full), injecting silence to compensate
[Warning: Unity Log] [Dissonance:Recording] (18:06:23.220) BasePreprocessingPipeline: Lost 480 samples in the preprocessor (buffer full), injecting silence to compensate
[Warning: Unity Log] [Dissonance:Recording] (18:06:23.220) BasePreprocessingPipeline: Lost 480 samples in the preprocessor (buffer full), injecting silence to compensate
[Warning: Unity Log] [Dissonance:Recording] (18:06:23.233) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:1.875896)" happened right after I unpaused the CMD window causing the music to stop.

**Comment by AndrewM521** [comment]
Boombox Controller version 1.1.7 seems to have fixed the BepInEx directory exception. As far as issue 3 goes, I am an idiot and didn't know that I had to left click when holding the boombox to start the music. I just assumed that it auto started when uploading a new song/playlist to the boombox. Maybe the auto start could be addition for next update, but that is up to you.

Thank you for the help and patience

**Comment by Koder-Teh** [comment]
> Boombox Controller version 1.1.7 seems to have fixed the BepInEx directory exception. As far as issue 3 goes, I am an idiot and didn't know that I had to left click when holding the boombox to start the music. I just assumed that it auto started when uploading a new song/playlist to the boombox. Maybe the auto start could be addition for next update, but that is up to you.
> 
> Thank you for the help and patience
Бывает XD. Спасибо что отписал о проблеме :) Когда время будет возможно и сделаю это.
