### ISSUE TITLE
Game crashes after adding link

### ISSUE THREAD

**Issue by Aleorhon** [Koder-Teh/Boombox-Controller#22]
Whenever someone adds a link to the boombox after uploading track my game crashes, happens only to me. My friends can put music and their game wont crash.

**Comment by wabash1** [comment]
It's probably crashing while converting or writing to your drive...


assuming you already rebooted your pc....
Uninstall game.
Delete lethal company files for mod, delete folder for lethal company. 
redownload
if that fails uninstall current antivirus, try again.
chkdsk /f /r
all else fails reinstall or repair install windows.

**Comment by Koder-Teh** [comment]
> Whenever someone adds a link to the boombox after uploading track my game crashes, happens only to me. My friends can put music and their game wont crash.

Привет! Скинь мне логи BepInEx. Так же скинь мне logReport.txt по пути "Lethal Company\BoomboxController\logReport.txt"

**Comment by Aleorhon** [comment]
Fixed by deleting all mods and game, then reinstalling again. Thank you!
