### ISSUE TITLE
Ссылка не действительная(

### ISSUE THREAD

**Issue by Thief365** [Koder-Teh/Boombox-Controller#23]
Пытаюсь насладится музыкой с бумбокса, не получается, в чём может быть проблема?((
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/156368179/458e2c82-640b-4b12-8874-2231c8103f2a)

**Comment by wabash1** [comment]
disable all mods except boombox and bepinex. restart lethal company. try again. are you using  r2 modman?

**Comment by Koder-Teh** [comment]
> Пытаюсь насладится музыкой с бумбокса, не получается, в чём может быть проблема?(( ![image](https://private-user-images.githubusercontent.com/156368179/296043314-458e2c82-640b-4b12-8874-2231c8103f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDczMTYsIm5iZiI6MTcwNTA0NzAxNiwicGF0aCI6Ii8xNTYzNjgxNzkvMjk2MDQzMzE0LTQ1OGUyYzgyLTY0MGItNGIxMi04ODc0LTIyMzFjODEwM2YyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwODEwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTA5MjI1Njk5MzczYzM0Njg3NzFjMzM5MTM5OTI0NzJiYjdhNzlmNTA1OWIzM2ZkYjQyZTJiNjRmYWE0MTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iLdVvPNpx4q1kto6wmn-5c9wTbpQZpi_tS01qTq3V8g)

Привет! Скинь мне логи BepInEx.
