### ISSUE TITLE
Can't add songs

### ISSUE THREAD

**Issue by NinoNikoles** [Koder-Teh/Boombox-Controller#24]
Either there is no message at all when trying to add a song or it says I'm too far away. But I have it equiped

**Comment by NinoNikoles** [comment]
*Problem is because of the Boombox_Sync_Fix mod

**Comment by Koder-Teh** [comment]
> *Problem is because of the Boombox_Sync_Fix mod

![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/bf6c2a1a-1897-4470-9a98-b36cc13ca4b5)
Спасибо за понимание.
