### ISSUE TITLE
Slow song loading "Please Wait" with youtube links, youtube music

### ISSUE THREAD

**Issue by lollykeps** [Koder-Teh/Boombox-Controller#25]
all the time when im trying to add song to the boombox with youtube link its loading for like 2-3 minutes... but when im trying with soundcloud everything ok its downloading in 5 sec...

can you please help me?

(My download speed are really good.. 1000mb per sec)

**Comment by Koder-Teh** [comment]
Привет! Сейчас я постараюсь объяснить в чем проблема. Когда ты запускаешь ссылку через Youtube. У программы больше происходит манипуляций нежели, запуск ссылки через SoundCloud. Поэтому и время больше требуется на загрузку. Грубо говоря ссылку через Youtube, конвертировать в правильное расширение файла. Которое понимает самая игра. А у SoundCloud, он изначально идет в правильном расширении файла. Поэтому он быстрее загружает. Я стараюсь над этим работать, но как я понял это максимум что я могу ускорить. Хотя я еще посмотрю. Спасибо что написали мне о проблеме. Буду стараться ее решить.

**Comment by wabash1** [comment]
It's a limitation of your CPU not your internet, soundcloud is already in a format the game can understand so not needed to convert or very minimal conversion, with youtube your pc has to transcode the file.
