### ISSUE TITLE
cant find boombox controller config when using mod managers

### ISSUE THREAD

**Issue by t6rtar** [Koder-Teh/Boombox-Controller#27]
Cannot find the boombox controller config when using mod managers
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/155864427/fc144edd-1e33-4c02-ad0c-d61de955a99a)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/155864427/7ebc4f95-effa-4ca9-8c7b-aabd53986e19)

suggestion: make it so that when you pause and continue a song, it'll play from where you stopped like spotify and start the song right away after uploading

is there a way to fix the lag when the song finishes loading

**Comment by Koder-Teh** [comment]
> Cannot find the boombox controller config when using mod managers ![image](https://private-user-images.githubusercontent.com/155864427/296498350-fc144edd-1e33-4c02-ad0c-d61de955a99a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjgzMzksIm5iZiI6MTcwNTIyODAzOSwicGF0aCI6Ii8xNTU4NjQ0MjcvMjk2NDk4MzUwLWZjMTQ0ZWRkLTFlMzMtNGMwMi1hZDBjLWQ2MWRlOTU1YTk5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMDI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTYwNDczY2E0N2RjZDIzMDA3ZjAyZjMzNjkwMmU3MDc0Y2Y2OWU3M2U3ZTE0OTcxNDIwNjE1ZWFhMjk0NjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QKXaix368FRXmC9_h4BkOv8vw1Dkp1hPomH5UwoNzoc) ![image](https://private-user-images.githubusercontent.com/155864427/296498372-7ebc4f95-effa-4ca9-8c7b-aabd53986e19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjgzMzksIm5iZiI6MTcwNTIyODAzOSwicGF0aCI6Ii8xNTU4NjQ0MjcvMjk2NDk4MzcyLTdlYmM0Zjk1LWVmZmEtNGNhOS04YzdiLWFhYmQ1Mzk4NmUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMDI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmFlYmUwYmUwMGQ3MTQ4NzE1ZTNhMDczOTVjNGRmNjA4NDhjNGI0NzZhYmQ4ZGE5YmZkOGNhZTk1NjM0YzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1W0hCLQO2tLhLSU8yStGViLwSFfmyNVRlRN-JCf0Dk)

Привет! Поддержки r2modman нету у мода.

> suggestion: make it so that when you pause and continue a song, it'll play from where you stopped like spotify and start the song right away after uploading

Хорошее предложение. В следующих обновлениях возможно сделаю.

> is there a way to fix the lag when the song finishes loading

Можешь уточнить какая задержка?

**Comment by t6rtar** [comment]
> > Cannot find the boombox controller config when using mod managers ![image](https://private-user-images.githubusercontent.com/155864427/296498350-fc144edd-1e33-4c02-ad0c-d61de955a99a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjgzMzksIm5iZiI6MTcwNTIyODAzOSwicGF0aCI6Ii8xNTU4NjQ0MjcvMjk2NDk4MzUwLWZjMTQ0ZWRkLTFlMzMtNGMwMi1hZDBjLWQ2MWRlOTU1YTk5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMDI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTYwNDczY2E0N2RjZDIzMDA3ZjAyZjMzNjkwMmU3MDc0Y2Y2OWU3M2U3ZTE0OTcxNDIwNjE1ZWFhMjk0NjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QKXaix368FRXmC9_h4BkOv8vw1Dkp1hPomH5UwoNzoc) ![image](https://private-user-images.githubusercontent.com/155864427/296498372-7ebc4f95-effa-4ca9-8c7b-aabd53986e19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjgzMzksIm5iZiI6MTcwNTIyODAzOSwicGF0aCI6Ii8xNTU4NjQ0MjcvMjk2NDk4MzcyLTdlYmM0Zjk1LWVmZmEtNGNhOS04YzdiLWFhYmQ1Mzk4NmUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMDI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmFlYmUwYmUwMGQ3MTQ4NzE1ZTNhMDczOTVjNGRmNjA4NDhjNGI0NzZhYmQ4ZGE5YmZkOGNhZTk1NjM0YzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1W0hCLQO2tLhLSU8yStGViLwSFfmyNVRlRN-JCf0Dk)
> 

https://github.com/Koder-Teh/Boombox-Controller/assets/155864427/d936b5bd-97f1-4124-9768-0d9989bf7b12
> 
> > suggestion: make it so that when you pause and continue a song, it'll play from where you stopped like spotify and start the song right away after uploading
> 
> Хорошее предложение. В следующих обновлениях возможно сделаю.
> 
> > is there a way to fix the lag when the song finishes loading
> 
> Можешь уточнить какая задержка?
Specifically when you use /bplay and the song finishes loading, there is this big

**Comment by t6rtar** [comment]
> > Cannot find the boombox controller config when using mod managers ![image](https://private-user-images.githubusercontent.com/155864427/296498350-fc144edd-1e33-4c02-ad0c-d61de955a99a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjgzMzksIm5iZiI6MTcwNTIyODAzOSwicGF0aCI6Ii8xNTU4NjQ0MjcvMjk2NDk4MzUwLWZjMTQ0ZWRkLTFlMzMtNGMwMi1hZDBjLWQ2MWRlOTU1YTk5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMDI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTYwNDczY2E0N2RjZDIzMDA3ZjAyZjMzNjkwMmU3MDc0Y2Y2OWU3M2U3ZTE0OTcxNDIwNjE1ZWFhMjk0NjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QKXaix368FRXmC9_h4BkOv8vw1Dkp1hPomH5UwoNzoc) ![image](https://private-user-images.githubusercontent.com/155864427/296498372-7ebc4f95-effa-4ca9-8c7b-aabd53986e19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjgzMzksIm5iZiI6MTcwNTIyODAzOSwicGF0aCI6Ii8xNTU4NjQ0MjcvMjk2NDk4MzcyLTdlYmM0Zjk1LWVmZmEtNGNhOS04YzdiLWFhYmQ1Mzk4NmUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMDI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmFlYmUwYmUwMGQ3MTQ4NzE1ZTNhMDczOTVjNGRmNjA4NDhjNGI0NzZhYmQ4ZGE5YmZkOGNhZTk1NjM0YzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1W0hCLQO2tLhLSU8yStGViLwSFfmyNVRlRN-JCf0Dk)
> 
> Привет! Поддержки r2modman нету у мода.
> 
> > suggestion: make it so that when you pause and continue a song, it'll play from where you stopped like spotify and start the song right away after uploading
> 
> Хорошее предложение. В следующих обновлениях возможно сделаю.
> 
> > is there a way to fix the lag when the song finishes loading
> 
> Можешь уточнить какая задержка?
in the video around 0:07, after using /bplay, there is this lag that occurs. maybe due to the song file getting uploaded. 

https://github.com/Koder-Teh/Boombox-Controller/assets/155864427/92b6acf7-e5ab-4eef-8c0e-534693b587e7
