### ISSUE TITLE
Playlist order desync

### ISSUE THREAD

**Issue by JoJoCheck** [Koder-Teh/Boombox-Controller#29]
I was playing with friends and made a playlist on Youtube that we all could add songs to. But after we uploaded the playlist to Lethal Company, everyone's track order was different. While someone heard song Number 1, another person heard song Number 5 and another heard song Number 7.

I don't know if this is a problem with the game or this mod. Any idea what the issue could be?

**Comment by Koder-Teh** [comment]
> I was playing with friends and made a playlist on Youtube that we all could add songs to. But after we uploaded the playlist to Lethal Company, everyone's track order was different. While someone heard song Number 1, another person heard song Number 5 and another heard song Number 7.
> 
> I don't know if this is a problem with the game or this mod. Any idea what the issue could be?

Привет! Насчет того что плейлист запускает не по порядку песни, это так и должно быть. А вот насчет что каждый слышит разные песни, так не должно быть. Скинь мне логи BepInEx. И скинь плейлист который запускаешь.

**Comment by JoJoCheck** [comment]
Sorry for the late reply, here is the log file from a testing session me and a friend just did, the issue was still present.
[LogOutput - Kopie.log](https://github.com/Koder-Teh/Boombox-Controller/files/13967821/LogOutput.-.Kopie.log)

And this is the Playlist we used.
https://www.youtube.com/playlist?list=PLvawL6zMrbXllpd01NTzDPlV-3Rfs0al1

**Comment by Koder-Teh** [comment]
> Sorry for the late reply, here is the log file from a testing session me and a friend just did, the issue was still present. [LogOutput - Kopie.log](https://github.com/Koder-Teh/Boombox-Controller/files/13967821/LogOutput.-.Kopie.log)
> 
> And this is the Playlist we used. https://www.youtube.com/playlist?list=PLvawL6zMrbXllpd01NTzDPlV-3Rfs0al1

Привет! Не заметил ошибок в логах. Плейлист загружается. Я пока закрою тему. Если будет какие то проблемы, создайте новую тему либо откройте эту.
