### ISSUE TITLE
Boombox appears in hand when equipping other items 

### ISSUE THREAD

**Issue by klsadjlkdjad** [Koder-Teh/Boombox-Controller#30]
self explanatory I use reserved boombox slot, boombox overhaul, and weightless boombox, I also had to manually add the config file because it wouldn't do it automatically.
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/71944000/2aa423bf-88b9-402d-8975-a09c92f09366)

**Comment by wabash1** [comment]
Most likely those mods are conflicting. Remove all mods, add one back at a time. possibly add  back weightless first, then overhaul, then reserved slot.

**Comment by Koder-Teh** [comment]
Привет!

> self explanatory I use reserved boombox slot

Мне не очевидно что ты используешь доп. резервный слот для бумбокса.

> weightless boombox

В новом обновление я добавил вес у бумбокса 0.

> I also had to manually add the config file because it wouldn't do it automatically.

Какой файл cfg? Если конфиг другого мода. То я за них не отвечаю.
