### ISSUE TITLE
Where are the songs getting dowloaded/ saved too? Is there a way to edit the list of songs "uploaded" to the boombox?

### ISSUE THREAD

**Issue by JVB-code** [Koder-Teh/Boombox-Controller#31]
The given commands dont give a option for deleting or managing the "uploaded" tracks. What is the best way to do it. 
Sry if the asked question is dumb or the answer is too obvious. I have no cfg file for the boombox mod in the config or in the Boombox controller folder.
Thanks for the help in advance.

Russian Translation:

Данные команды не дают опции для удаления или управления «загруженными» треками.Как лучше всего это сделать.
Sry, если задающий вопрос тупой или ответ слишком очевиден. У меня нет файла CFG для мода Boombox в конфигурации или в папке контроллера Boombox.
Спасибо за помощь в продвижении.

**Comment by Koder-Teh** [comment]
> The given commands dont give a option for deleting or managing the "uploaded" tracks. What is the best way to do it. Sry if the asked question is dumb or the answer is too obvious. I have no cfg file for the boombox mod in the config or in the Boombox controller folder. Thanks for the help in advance.
> 
> Russian Translation:
> 
> Данные команды не дают опции для удаления или управления «загруженными» треками.Как лучше всего это сделать. Sry, если задающий вопрос тупой или ответ слишком очевиден. У меня нет файла CFG для мода Boombox в конфигурации или в папке контроллера Boombox. Спасибо за помощь в продвижении.

Привет! У меня в моде нету таких опций к редактированию загруженных треков. Файл cfg должен быть по пути: "Lethal Company\BoomboxController".
