### ISSUE TITLE
Boombox message: Please wait, additional libraries are being loaded for the modifictation to work.

### ISSUE THREAD

**Issue by Daniel-M-P** [Koder-Teh/Boombox-Controller#32]
This messages appears on top of the boombox when bought 
![Screenshot 2024-01-16 155037](https://github.com/Koder-Teh/Boombox-Controller/assets/16928786/a81c2389-1ee3-4df4-b5c7-eb908b1d6917)

And it nevers ends to load the libraries, I think it has to do with these two messages that appear again and again in the BepInEx log:

[Warning: Unity Log] Audio source failed to initialize audio spatializer. An audio spatializer is specified in the audio project settings, but the associated plugin was not found or initialized properly. Please make sure that the selected spatializer is compatible with the target.

[Info   :RugbugRedfern.SkinwalkerMod] Audio folder not present. Don't worry about it, it will be created automatically when you play with friends. (C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics)

What can I do to fix this and use the mod as usual??

**Comment by Koder-Teh** [comment]
> Это сообщение появляется поверх бумбокса при покупке. ![Скриншот 16.01.2024 155037](https://private-user-images.githubusercontent.com/16928786/297158647-a81c2389-1ee3-4df4-b5c7-eb908b1d6917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDgyNDIsIm5iZiI6MTcwNTUwNzk0MiwicGF0aCI6Ii8xNjkyODc4Ni8yOTcxNTg2NDctYTgxYzIzODktMWVlMy00ZGY0LWI1YzctZWI5MDhiMWQ2OTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNmUzODE0NzVjZWExOWRhNjUwZjAwNDRhNjRjMzc2NzgwODY1YWFmMTZiMjliYTc1MmI2ZmFhZmZmYzg3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V9hQkb5dvXzCbKVLmQVMKhDmQWSxiBrbWdgmaKhgz7c)
> 
> И загрузка библиотек никогда не заканчивается, я думаю, это связано с этими двумя сообщениями, которые снова и снова появляются в журнале BepInEx:
> 
> [Предупреждение: журнал Unity] Источнику звука не удалось инициализировать пространственный преобразователь звука. В настройках аудиопроекта указан пространственный преобразователь звука, но соответствующий плагин не был найден или инициализирован должным образом. Убедитесь, что выбранный пространственный преобразователь совместим с целью.
> 
> [Информация: RugbugRedfern.SkinwalkerMod] Папка Audio отсутствует. Не беспокойтесь об этом, он будет создан автоматически, когда вы играете с друзьями. (C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data..\Dissonance_Diagnostics)
> 
> Что я могу сделать, чтобы исправить это и использовать мод как обычно??

Привет! Нечего, тупо подождать когда установится доп. библиотеки. Скачивание зависит от скорости интернета.
