### ISSUE TITLE
[Вопрос] Можно ли заранее скачать музыку?

### ISSUE THREAD

**Issue by Daoprotoss** [Koder-Teh/Boombox-Controller#38]
Можно ли заранее скачать музыку и оставить её где-то, чтобы при запуске игры, заранее сохраненные треки записались в игру?

**Comment by Koder-Teh** [comment]
Привет! Мне уже поэтому поводу писали как предложение для обновления. В следующем обновления я это сделаю, наверное через отдельную команду.
