### ISSUE TITLE
Commands not working for Boombox Controller

### ISSUE THREAD

**Issue by AlexGamerNice** [Koder-Teh/Boombox-Controller#4]
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/64309667/906430b5-dc6a-4bb6-9435-146b8d8a665c)
 
When I press enter it just simply says 
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/64309667/de0adffc-be32-4fb8-a3ec-ce89d385bd0c)
 I have a boombox next to me. Please tell me if i missed anything

**Comment by Koder-Teh** [comment]
Привет, команды надо вводить в чате. А не в терминале 😆😆

**Comment by AlexGamerNice** [comment]
oh...
