### ISSUE TITLE
Problems with playing local music and ThunderStore manager

### ISSUE THREAD

**Issue by BAHEK-BOP** [Koder-Teh/Boombox-Controller#46]
I noticed a few problems

1.(IMPORTANT) Error downloading and searching for music through the Thunderstore Mod Manager app (photo 7).  
At least my photo matches what you wrote on your page. alas, this does not work, the Thunderstore Mod Manager unpacker works in a completely different way (photo 1). Can you fix it somehow? I tried to do this:

Thunderstore Mod Manager\LethalCompany\profiles\bmlc\BepInEx\plugins\BAHEK_BOP-CustomBoomBox_BAHEK_BOP\BoomboxController\other\local

I know it's not right. But Thunderstore Mod Manager does not give me the opportunity to unpack in the folder with the game. 
to make it look like this:

Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\bmlc\BoomboxController\other\local

2. (SLIGHTLY) Did as you asked where exactly to move the folder. When the game was running, alas, the game could not see that I had added music(photo 2,3). Plus, I caught some kind of bug when, during the game, the boombox tried to process the music, But I only got Typing and it happened that after / I broke the game and couldn't move, although my chat was closed (photo 4,5).  I fixed it with the restart of the game, then the lashes started and I realized that my music was being loaded into the boombox(photo 6)

3.(AVERAGE) The second error is not critical, but what about the lags that occur when downloading music?  Can I add a music check for the boombox when starting the game? so at least we'll get rid of the lags, and leave the /bload command so that the music is updated when new songs are uploaded. And I'll put up with a little longer launch of the game.  

4. (IMPORTANT) Is it possible to do something for the local mode so that a person does not enter /btrack <track number> all the time and the music is randomly selected, or the next one in the list is played when pressing the LMB? 

The logic is as follows: I picked up the boombox, pressed the LMB, music began to play, for example, under the name TRACK1, I pressed the LMB again, the music stopped playing, I pressed the LMB again, music called TRACK7 began to play, etc.

I have given some of my questions a level of importance, answer at least 1 and 4 if you can
================
Я заметил несколько проблем

1. (ВАЖНО) Ошибка загрузки и поиск музыки через приложение Thunderstore Mod Manager (фото 7).
 Я попытался запаковать архив так, как  вы написали на своей странице. увы, это не работает, распаковщик Thunderstore Mod Manager работает совершенно по-другому (фото 1). Вы можете это как-то исправить? Я пытался это сделать:

Thunderstore Mod Manager\LethalCompany\profiles\bmlc\BepInEx\plugins\BAHEK_BOP-CustomBoomBox_BAHEK_BOP\BoomboxController\other\local

Я знаю, что это неправильно. Но менеджер модов Thunderstore не дает мне возможности распаковать в папку с игрой.
чтобы это выглядело так:

Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\bmlc\BoomboxController\other\local

2. (НЕЗНАЧИТЕЛЬНО) Во врем игры, попытался запихнуть музыку в папку как у вас и написано на странице с модом. Когда игра запускалась, увы, игра не могла видеть, что я добавил музыку (фото 2,3). Плюс, я поймал какую-то ошибку, когда во время игры бумбокс пытался обработать музыку, но у меня получалось только печатать, и случилось так, что после / я сломал игру и не мог двигаться, хотя мой чат был закрыт (фото 4,5). Я исправил это перезапуском игры, затем начались фризы, и я понял, что моя музыка загружается в бумбокс (фото 6)

3. (СРЕДНЕЕ) Вторая ошибка не критична, но как насчет фризов, возникающих при загрузке музыки? Можно ли добавить проверку музыки для бумбокса при запуске игры?  по крайней мере, мы избавимся от лагов и оставим команду /bload, чтобы музыка обновлялась при загрузке новых песен. Я смирюсь с немного более длительным запуском игры.

4. (ВАЖНО) Можно ли что-то сделать для локального режима, чтобы человек не вводил /btrack <track number> все время, и музыка выбиралась случайным образом, или при нажатии LMB воспроизводилась следующая в списке?

Логика заключается в следующем: Я взял бумбокс, нажал LMB, начала воспроизводиться музыка, например, под названием TRACK1, я снова нажал LMB, музыка перестала воспроизводиться, я снова нажал LMB, начала воспроизводиться музыка под названием TRACK7 и т.д.

Я придал некоторым своим вопросам уровень важности, ответьте хотя бы на 1 и 4, если сможете
-----
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/a42f10a9-b115-4071-b983-65d4d5c38aeb)

![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/766a6714-7ac3-4eaa-bd85-a3352480089f)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/c16b8e0e-b6e9-407e-9b7d-5ba192fb343d)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/fc1f6943-44f9-4a88-a609-d5829aa6533c)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/6d7445e9-e299-4ca1-87b1-2fb55ba8a863)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/9f935c1a-17db-4c8f-a231-c015e2b62168)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/ad4fcdb7-89c6-4044-b93e-14ca53bfebe8)

**Comment by BAHEK-BOP** [comment]
I noticed something else, the music sometimes gets stuck on one track. I have a boombox loaded with over 50 songs. but at 19 he got up and stupidly turned it around in a circle, although before that he started the next one when the song that was playing in the boombox ended

**Comment by BAHEK-BOP** [comment]
I forgot something else. There are no new commands in the /bhelp list
/bswitch local 
/bswitch net
/bload

**Comment by Koder-Teh** [comment]
Привет! Спасибо что так много расписал. Насчет проблем, начну потихоньку объяснять.

> 1. (ВАЖНО) Ошибка загрузки и поиск музыки через приложение Thunderstore Mod Manager (фото 7).
>    Я попытался запаковать архив так, как  вы написали на своей странице. увы, это не работает, распаковщик Thunderstore Mod Manager работает совершенно по-другому (фото 1). Вы можете это как-то исправить? Я пытался это сделать:
> 
> Thunderstore Mod Manager\LethalCompany\profiles\bmlc\BepInEx\plugins\BAHEK_BOP-CustomBoomBox_BAHEK_BOP\BoomboxController\other\local
> 
> Я знаю, что это неправильно. Но менеджер модов Thunderstore не дает мне возможности распаковать в папку с игрой. чтобы это выглядело так:
> 
> Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\bmlc\BoomboxController\other\local

Мод не поддерживает ThunderStore Mod Manager. Ну может пока что. У тебя где игра лежит? Если у тебя steam версия, то в папке с игрой, у тебя уже должна быть папка BoomboxController. То есть примерно вот так:
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/7e25450b-7c67-419f-a62e-0c5a5be3b4ab)
И вот в эту папку надо кидать файлы музыки. А не по пути ThunderStore Mod Manager. Опять же я не знаю всех этих тонкостей, с этим мод менеджером. Так как я пират. Опять же если я что-то не так понял, объясни и прикрепи скрины.

> 2. (НЕЗНАЧИТЕЛЬНО) Во врем игры, попытался запихнуть музыку в папку как у вас и написано на странице с модом. Когда игра запускалась, увы, игра не могла видеть, что я добавил музыку (фото 2,3). Плюс, я поймал какую-то ошибку, когда во время игры бумбокс пытался обработать музыку, но у меня получалось только печатать, и случилось так, что после / я сломал игру и не мог двигаться, хотя мой чат был закрыт (фото 4,5). Я исправил это перезапуском игры, затем начались фризы, и я понял, что моя музыка загружается в бумбокс (фото 6)

С начало надо закинуть музыку в папку, которую я указывал на странице мода.
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/f3813ed8-12ce-4c48-b327-7ebecab36a04)
Потом зайти в игру, в лобби. И уже далее ввести команду /bswitch local. Это мы меняем режим мода. И после введение этой команды, музыка должна загрузится в игру. 

> 3. (СРЕДНЕЕ) Вторая ошибка не критична, но как насчет фризов, возникающих при загрузке музыки? Можно ли добавить проверку музыки для бумбокса при запуске игры?  по крайней мере, мы избавимся от лагов и оставим команду /bload, чтобы музыка обновлялась при загрузке новых песен. Я смирюсь с немного более длительным запуском игры.

Я не хочу перекладывать загрузку песен при запуске игры. Мне кажется проще переписать чутка метод загрузки песен, под асинхронный поток. В следующем обновление я исправлю это.

> 4. (ВАЖНО) Можно ли что-то сделать для локального режима, чтобы человек не вводил /btrack  все время, и музыка выбиралась случайным образом, или при нажатии LMB воспроизводилась следующая в списке?
> 
> Логика заключается в следующем: Я взял бумбокс, нажал LMB, начала воспроизводиться музыка, например, под названием TRACK1, я снова нажал LMB, музыка перестала воспроизводиться, я снова нажал LMB, начала воспроизводиться музыка под названием TRACK7 и т.д.

Как я понял ты хочешь чтобы я реализовал рандомный выбор песен, принципе я могу мне не сложно. Тогда тоже добавлю в следующем обновлении.

> Я придал некоторым своим вопросам уровень важности, ответьте хотя бы на 1 и 4, если сможете

Конечно я смогу ответить. Как иначе :)

> Я заметил кое-что еще, музыка иногда застревает на одном треке. У меня в бумбоксе загружено более 50 песен. Но на 19 треке он встал и тупо прокрутил ее по кругу, хотя перед этим начал следующую, когда закончилась песня, которая играла в бумбоксе

Желательно записать этот момент на видео, чтобы мне точно посмотреть как ошибка это проявляется. Так же надо скинуть логи BepInEx. И файл который лежит по пути "Lethal Company\BoomboxController\logReport.txt"

> I forgot something else. There are no new commands in the /bhelp list /bswitch local /bswitch net /bload

Я не добавил потому что, спать хотел очень сильно. Да и место нету куда это все добавлять. Чат и так засоряется текстами.

**Comment by BAHEK-BOP** [comment]
[Koder-Tech](https://github.com/Koder-Teh)
Как же хорошо, с тобой на родном языке, хоть у меня английский ниже среднего, но некоторые сложности в написании проблем могут быть.  Продолжу так же по вопросам

1. У меня стим версия, я просто создал свой модпак под 100+ модов BMLC называется. можешь на сайте тандерстор глянуть или в поиск вбить, он должен ссылку тебе дать. Я поддерживаю связь в своем дс сервере, если какие ошибки или проблемы имеются я их по возможности устраняю. https://discord.gg/3C6BQqe79R . Можешь зайти сам глянуть... 

Вот вернусь к теме, мне просто удобна сама методика тестов и загрузки модификаций через их приложение. Вот как это выглядит 
![Безымянный](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/1c9d836b-22ed-4272-a4e7-6dfea64eac72)
А само расположение папки находится вот где:
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/4da951c1-a5b8-4c5d-8d97-ee245aa527d9)

Конечный путь выглядит вот так:
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/167521b7-e31b-43d2-a882-18b4e87e3060)

Как видишь здесь папка уже есть, это я собственно ручно ее туда поставил. Все как ты писал по твоей инструкции 
НО. Смотри какое дело, я сделал свой пак музыки, и хочу чтобы он встал по пути так как ты просишь (ну что бы все работало). Для этого я отдельно создаю папку BepInEx и BoomboxController в архиве это выглядит так: 

По моей логике распаковки он что, должен был сделать, запихнуть это все в корень игры и не трогать. все в моем архиве в папке BepInEx закинуть локальную папку игры и где то там должен был зачесаться папка BoomboxController , и оставить папку с названием мода в папке Plugins вместе со всеми зависимыми, manifest, changelog, icon и т.д

Но логика распаковки  у менеджера другая и я щас ее тебе покажу: 
https://youtu.be/_jJNrhiqs_U

В видео все рассказал показал, рассказал так же про 4 вопрос, но я потом еще продублирую.  И да мне пришлось твой мод отключить а то они оба не работают) (просто если возникнет вопрос, а че тогда и этот мод себе не поставишь в модпак, или для игры? ответ: Мне твой мод понравился что можно загружать музыку как через ютуб так и через саундкланд и другие сервисы, так еще тут и оффлайн загрузка музыки, вообще отвал башки).)

| Желательно записать этот момент на видео, чтобы мне точно посмотреть как ошибка это проявляется. Так же надо скинуть логи BepInEx. И файл который лежит по пути "Lethal Company\BoomboxController\logReport.txt"

Ну и по вопросу с загрузкой я как баг поймаю тебе видео кину и покажу консоль

**Comment by BAHEK-BOP** [comment]
Короче вот что заметил 
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/7c83e4d4-62f1-43e1-878b-3d880d34d756)
музыка проигрывается но, когда смотрю на него то в нем пусто в консоли пусто
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/220ecdd3-a92f-4e9b-9c88-d2b15880910b)
Я как и говорил это лечится если я другу песню поставлю (точнее как, мне пришлось песню остановить и заново ее запустить)
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/157053836/41c9cd36-cab4-4c9f-9f55-8a7045dac057)

**Comment by Koder-Teh** [comment]
> [Koder-Tech](https://github.com/Koder-Teh) Как же хорошо, с тобой на родном языке, хоть у меня английский ниже среднего, но некоторые сложности в написании проблем могут быть. Продолжу так же по вопросам
> 
> 1. У меня стим версия, я просто создал свой модпак под 100+ модов BMLC называется. можешь на сайте тандерстор глянуть или в поиск вбить, он должен ссылку тебе дать. Я поддерживаю связь в своем дс сервере, если какие ошибки или проблемы имеются я их по возможности устраняю. https://discord.gg/3C6BQqe79R . Можешь зайти сам глянуть...
> 
> Вот вернусь к теме, мне просто удобна сама методика тестов и загрузки модификаций через их приложение. Вот как это выглядит ![Безымянный](https://private-user-images.githubusercontent.com/157053836/302427754-1c9d836b-22ed-4272-a4e7-6dfea64eac72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODQyNzEsIm5iZiI6MTcwNzI4Mzk3MSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNDI3NzU0LTFjOWQ4MzZiLTIyZWQtNDI3Mi1hNGU3LTZkZmVhNjRlYWM3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNTMyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzFhNjRhNzdkNWVkMDVmMTgyYjdkYzFlNmM0N2UxNzM4YjlkMjU2Y2E1NzFhMzI5YTE3YzQzNDBhNzE5YTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NOoOIdQVpECpeuQ9aHmPYsh_tkMY9M59D_UDi_N1-94) А само расположение папки находится вот где: ![image](https://private-user-images.githubusercontent.com/157053836/302427893-4da951c1-a5b8-4c5d-8d97-ee245aa527d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODQyNzEsIm5iZiI6MTcwNzI4Mzk3MSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNDI3ODkzLTRkYTk1MWMxLWE1YjgtNGM1ZC04ZDk3LWVlMjQ1YWE1MjdkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNTMyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDAxZTc5MDlhNThlZTlmOTBiNzE4OWJkZmFhMzY0NzZkY2ViZWFhMjRkZTQ3ZjMzYmE0ZTk2NGNhNzc3YmM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZAKiffmwi4NrVHJhPhhfDlaHdkYFeCjzOwmaUZj0sGE)
> 
> Конечный путь выглядит вот так: ![image](https://private-user-images.githubusercontent.com/157053836/302427988-167521b7-e31b-43d2-a882-18b4e87e3060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODQyNzEsIm5iZiI6MTcwNzI4Mzk3MSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNDI3OTg4LTE2NzUyMWI3LWUzMWItNDNkMi1hODgyLTE4YjRlODdlMzA2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNTMyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTQ2YzZhZTkzODM5ZmEzNTZlODliOTNmNmI2OGNkNWYyNWYzOWVlMDMxZTM1YjVmMzZjM2Y1NzQ2NzU2NmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iGI9R1kRL4G7gjUFTVc8hnYfk5O7-xK7nYcvhuk11A4)
> 
> Как видишь здесь папка уже есть, это я собственно ручно ее туда поставил. Все как ты писал по твоей инструкции НО. Смотри какое дело, я сделал свой пак музыки, и хочу чтобы он встал по пути так как ты просишь (ну что бы все работало). Для этого я отдельно создаю папку BepInEx и BoomboxController в архиве это выглядит так:
> 
> По моей логике распаковки он что, должен был сделать, запихнуть это все в корень игры и не трогать. все в моем архиве в папке BepInEx закинуть локальную папку игры и где то там должен был зачесаться папка BoomboxController , и оставить папку с названием мода в папке Plugins вместе со всеми зависимыми, manifest, changelog, icon и т.д
> 
> Но логика распаковки у менеджера другая и я щас ее тебе покажу: https://youtu.be/_jJNrhiqs_U
> 
> В видео все рассказал показал, рассказал так же про 4 вопрос, но я потом еще продублирую. И да мне пришлось твой мод отключить а то они оба не работают) (просто если возникнет вопрос, а че тогда и этот мод себе не поставишь в модпак, или для игры? ответ: Мне твой мод понравился что можно загружать музыку как через ютуб так и через саундкланд и другие сервисы, так еще тут и оффлайн загрузка музыки, вообще отвал башки).)
> 
> | Желательно записать этот момент на видео, чтобы мне точно посмотреть как ошибка это проявляется. Так же надо скинуть логи BepInEx. И файл который лежит по пути "Lethal Company\BoomboxController\logReport.txt"
> 
> Ну и по вопросу с загрузкой я как баг поймаю тебе видео кину и покажу консоль

Привет! Я как понял ты хочешь распаковать саунды автоматически при установке, и чтобы мод считывал их? Давай я для твоей сборки, сделаю пути для проверки саундов. Так же могу твою сборку закинуть как дополнение к моему моду на сайте тунедрстор. Опять же если хочешь. Насчет рандомной музыки, я принципе понял ситуацию. Сегодня я ее реализую.

> Короче вот что заметил ![image](https://private-user-images.githubusercontent.com/157053836/302453028-7c83e4d4-62f1-43e1-878b-3d880d34d756.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODQyNzEsIm5iZiI6MTcwNzI4Mzk3MSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNDUzMDI4LTdjODNlNGQ0LTYyZjEtNDNlMS04NzhiLTNkODgwZDM0ZDc1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNTMyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDA4YzIwZDIyMGNiNDZkOGExZjU3YWE3MDM5ODQzOTc5ZjBhMTk5NDFiYWY4NmY4ZTI4YTIzNWUzZTU4YjNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ug1kBmcP11eHyY71nCZ3coYKkwAtezNqaPYLVZDvsE8) музыка проигрывается но, когда смотрю на него то в нем пусто (время не идет) и в консоли пусто ![image](https://private-user-images.githubusercontent.com/157053836/302453152-220ecdd3-a92f-4e9b-9c88-d2b15880910b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODQyNzEsIm5iZiI6MTcwNzI4Mzk3MSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNDUzMTUyLTIyMGVjZGQzLWE5MmYtNGU5Yi05Yzg4LWQyYjE1ODgwOTEwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNTMyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTRkMGJmZjUwM2RlMTg2YzdkNWExNDc5NmJiMmUxZTBkOGMwNDFmZTgzNDZhZDQxZjNiMzg2MGIwOTEwM2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XisrmeL95tlBdrtiGPQKkXVrC9cnyN2ZhiX0-SFz0V4) Я как и говорил это лечится если я другую песню поставлю (точнее как, мне пришлось песню остановить и заново ее запустить) ![image](https://private-user-images.githubusercontent.com/157053836/302453310-41c9cd36-cab4-4c9f-9f55-8a7045dac057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODQyNzEsIm5iZiI6MTcwNzI4Mzk3MSwicGF0aCI6Ii8xNTcwNTM4MzYvMzAyNDUzMzEwLTQxYzljZDM2LWNhYjQtNGM5Zi05ZjU1LThhNzA0NWRhYzA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwNTMyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjA0Y2VkYzVhYjVhZWVmYzA1MDQ1M2FlNDk4MzIzMGVjODhhOTFhOWQ4ODY5MzA4YmM3MGFkZDlkNDdiMmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XgiVohVEIl_NDNv8Ee_C4gOR4b8fYxjbFfHS0yzgMso)

Насчет этого я хуй знает. Скорее всего не успевает менять значение переменная, которое за это отвечает. Опять же надо все обкатывать, и уже смотреть на результат. Спасибо что написал мне насчет этого. Ты приятный человек в общении.
