### ISSUE TITLE
multiplayer 

### ISSUE THREAD

**Issue by amirlime** [Koder-Teh/Boombox-Controller#47]
Why that not working
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/122648967/43c41728-219d-4806-a7a6-026876d16da8)

![image](https://github.com/Koder-Teh/Boombox-Controller/assets/122648967/168530dc-efdb-4336-bd8c-d5dc36177327)

**Comment by Koder-Teh** [comment]
Привет! Скинь мне логи BepInEx. Так же файл по пути "Lethal Company\BoomboxController\logReport.txt"

**Comment by BAHEK-BOP** [comment]
You have a problem with mods Helmet Camera https://thunderstorm.io/c/lethal-company/p/RickArg/Helmet_Cameras/ 

But not boombox controller

**Comment by amirlime** [comment]
Game Version: 49
Plugins: 24
ainavt.lc.lethalconfig G:\lethal\Lethal Company\BepInEx\plugins\LethalConfig\LethalConfig.dll
com.github.tinyhoot.ShipLoot G:\lethal\Lethal Company\BepInEx\plugins\ShipLoot\ShipLoot.dll
evaisa.lethallib G:\lethal\Lethal Company\BepInEx\plugins\LethalLib\LethalLib.dll
com.malco.lethalcompany.moreshipupgrades G:\lethal\Lethal Company\BepInEx\plugins\MoreShipUpgrades\MoreShipUpgrades.dll
com.rune580.LethalCompanyInputUtils G:\lethal\Lethal Company\BepInEx\plugins\LethalCompanyInputUtils\LethalCompanyInputUtils.dll
FlipMods.ReservedItemSlotCore G:\lethal\Lethal Company\BepInEx\plugins\ReservedItemSlotCore.dll
FlipMods.ReservedFlashlightSlot G:\lethal\Lethal Company\BepInEx\plugins\ReservedFlashlightSlot.dll
FlipMods.ReservedWalkieSlot G:\lethal\Lethal Company\BepInEx\plugins\ReservedWalkieSlot.dll
gravydevsupreme.xunity.autotranslator G:\lethal\Lethal Company\BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.BepInEx.dll
gravydevsupreme.xunity.resourceredirector G:\lethal\Lethal Company\BepInEx\plugins\XUnity.ResourceRedirector\XUnity.ResourceRedirector.BepInEx.dll
imabatby.lethallevelloader G:\lethal\Lethal Company\BepInEx\plugins\LethalLevelLoader.dll
KoderTech.BoomboxController G:\lethal\Lethal Company\BepInEx\plugins\BoomboxController.dll
LC_API G:\lethal\Lethal Company\BepInEx\plugins\2018-LC_API\LC_API.dll
me.swipez.melonloader.morecompany G:\lethal\Lethal Company\BepInEx\plugins\MoreCompany.dll
MaskedEnemyRework G:\lethal\Lethal Company\BepInEx\plugins\MaskedEnemyRework.dll
NicholaScott.BepInEx.RuntimeNetcodeRPCValidator G:\lethal\Lethal Company\BepInEx\plugins\NicholaScott.BepInEx.RuntimeNetcodeRPCValidator.dll
MoreEmotes G:\lethal\Lethal Company\BepInEx\plugins\MoreEmotes1.3.3.dll
RickArg.lethalcompany.helmetcameras G:\lethal\Lethal Company\BepInEx\plugins\HelmetCamera.dll
RugbugRedfern.SkinwalkerMod G:\lethal\Lethal Company\BepInEx\plugins\SkinwalkerMod.dll
snowflake.plugin.russiantranslateterminal G:\lethal\Lethal Company\BepInEx\plugins\RussianTranslateTerminal.dll
sunnobunno.YippeeMod G:\lethal\Lethal Company\BepInEx\plugins\YippeeMod.dll
viviko.BunkbedRevive G:\lethal\Lethal Company\BepInEx\plugins\BunkbedRevive.dll
x753.Mimics G:\lethal\Lethal Company\BepInEx\plugins\Mimics.dll
YT_BOOMBOX G:\lethal\Lethal Company\BepInEx\plugins\YT_BOOMBOX.dll

**Comment by amirlime** [comment]
вот логи

**Comment by BAHEK-BOP** [comment]
> вот логи

у тебя YT_BOOMBOX и KoderTech.BoomboxController  могут конфликтовать, но не до черного экрана

**Comment by Koder-Teh** [comment]
> Why that not working
> ![image](https://private-user-images.githubusercontent.com/122648967/302375129-43c41728-219d-4806-a7a6-026876d16da8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzMzODMsIm5iZiI6MTcwNzY3MzA4MywicGF0aCI6Ii8xMjI2NDg5NjcvMzAyMzc1MTI5LTQzYzQxNzI4LTIxOWQtNDgwNi1hN2E2LTAyNjg3NmQxNmRhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxNzM4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGUzYTU3ZjkzYjgxODEzNWYzNzVlZjM5YTc5ODg5MWU1NjgxMGU5MTk1NzE2MzJjMzk4ODA2YzhlMWUzYTQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FHn4a_YAoGC2i5XVIWmO7hOtRBopkgK2gC9bjUyU9c)

Привет! У тебя проблема с модом HelmetCamera, а не с моим.
