### ISSUE TITLE
boomboxcontroller crashes when loading playlists

### ISSUE THREAD

**Issue by brilliantshine** [Koder-Teh/Boombox-Controller#48]
I tried to load my playlist, but the mod said "Please wait..." and after that nothing else happened and I couldn't send any more chat messages. Here is the red text I found in the terminal from the mod manager.
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/43922048/e0240c4d-9950-4f9d-aab7-0d4cae1b7601)

**Comment by Koder-Teh** [comment]
> I tried to load my playlist, but the mod said "Please wait..." and after that nothing else happened and I couldn't send any more chat messages. Here is the red text I found in the terminal from the mod manager. ![image](https://private-user-images.githubusercontent.com/43922048/303817569-e0240c4d-9950-4f9d-aab7-0d4cae1b7601.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTA3OTksIm5iZiI6MTcwNzU1MDQ5OSwicGF0aCI6Ii80MzkyMjA0OC8zMDM4MTc1NjktZTAyNDBjNGQtOTk1MC00ZjlkLWFhYjctMGQ0Y2FlMWI3NjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA3MzQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YzVlM2M4MjQ0NGU5NTkyZmVmMDFiYjJkNjY0OWFkZThiNmFiYWM2MTQ5MDgxMjVjODZlNjM0ZWNmMmJmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y0gbU-95NOukDqSIFv7Wz6lGT-w4EnPbTPrBTFS9Hr0)

Привет! Скинь мне полностью логи BepInEx. Так же скинь плейлист который ты загружаешь

**Comment by brilliantshine** [comment]
Here are the log files!
[LogOutput.log](https://github.com/Koder-Teh/Boombox-Controller/files/14230508/LogOutput.log)
The playlist that I was trying to use was this one made by a friend, it is unlisted, is that okay?
https://www.youtube.com/playlist?list=PLsYERtpaLtNtCY4VGr0zWPfK6jBhGhffy
Thank you for the response. This mod is great and I will continue using it even if there is no playlist function.

**Comment by Koder-Teh** [comment]
Привет! Ошибку я уже исправил, сегодня будет выложен фикс.
