### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by AlmaPlata** [Koder-Teh/Boombox-Controller#5]
Hi, thanks a lot for the mod, me and my friends are enjoying it a lot.
If possible, could you make it so the .cfg file is relocated to the BeepInEx/config folder? Would make sharing a config through Thunderstore/r2modman modpacks a lot easier, since it can't really be done rn.

Thanks!

**Comment by Koder-Teh** [comment]
Привет, возможно. Но для этого мне понадобится много времени. Пока что я этим заниматься не думал, но все переменчиво. Может когда свободное время появится я переделаю.
