### ISSUE TITLE
[Suggestion] Prevent uploading if YouTube link is broken

### ISSUE THREAD

**Issue by FinniByh** [Koder-Teh/Boombox-Controller#50]
Accidentally our party paste the link to youtube without video ID like 'https://www.youtube.com/watch' (don't ask how it happened) and BoomBox started uploading every song from the main page. Could you please improve the validation of music links to avoid such cases?
![Screenshot_3](https://github.com/Koder-Teh/Boombox-Controller/assets/43145918/77dbaeee-4557-4cf0-a2e0-e045e0f61a33)

**Comment by Koder-Teh** [comment]
> Наша группа случайно вставила ссылку на YouTube без идентификатора видео типа « https://www.youtube.com/watch » (не спрашивайте, как это произошло), и BoomBox начал загружать каждую песню с главной страницы. Не могли бы вы улучшить проверку музыкальных ссылок, чтобы избежать подобных случаев? ![Скриншот_3](https://private-user-images.githubusercontent.com/43145918/303871391-77dbaeee-4557-4cf0-a2e0-e045e0f61a33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MjYzODAsIm5iZiI6MTcwNzYyNjA4MCwicGF0aCI6Ii80MzE0NTkxOC8zMDM4NzEzOTEtNzdkYmFlZWUtNDU1Ny00Y2YwLWEyZTAtZTA0NWUwZjYxYTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA0MzQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZDgyOWUwOTAxZDgyNWYwNDQzOGY0NzVmYzFmMjc0MmRhNTg4OWRiYmRkMmUxM2U2ZTY1ZDA1MWNmYzQwZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7tZDfOih1m0tomMLDbMJfaf8koWOMonfD83wddKjkYo)

Привет! АХХААХХАХАХАХААХАХАХ
