### ISSUE TITLE
Mod stops working after trying to play certain songs

### ISSUE THREAD

**Issue by Ex0ticButterzzz** [Koder-Teh/Boombox-Controller#61]
Certain songs will work and play fine, but some songs will refuse to play and break the mod till i delete the "other folder" to reset it. If a song breaks the mod I'm forced to restart the game and it gets annoying after a while.

https://github.com/user-attachments/assets/8f2d38fb-b874-4e89-9e3f-259f9d37c8cd

![image](https://github.com/user-attachments/assets/d228f0b5-0d64-46af-adbc-d2bcc9307c96)

**Comment by Koder-Teh** [comment]
> Некоторые песни будут работать и воспроизводиться нормально, но некоторые песни отказываются воспроизводиться и ломают мод, пока я не удалю "другую папку", чтобы сбросить его. Если песня ломает мод, мне приходится перезапускать игру, и через некоторое время это начинает раздражать.
> 
>  Без названия.видео.1.mp4 
> ![изображение](https://private-user-images.githubusercontent.com/81057195/369956604-d228f0b5-0d64-46af-adbc-d2bcc9307c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDI0MjIsIm5iZiI6MTcyNzUwMjEyMiwicGF0aCI6Ii84MTA1NzE5NS8zNjk5NTY2MDQtZDIyOGYwYjUtMGQ2NC00NmFmLWFkYmMtZDJiY2M5MzA3Yzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA1NDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMTczOGZmYzg1NjFhNjRhMzBmNWVlYzNkNWRiNTRmMmZhNTBjNTQ4NGZmOTJiMmY4OGE2MjM4NjYxZTBhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DnEsAeO2rLpVj5wY9x7res-Ed4JmDwPzJqJt44seVQk)

Привет! Баг я увидел. Сегодня выпущу исправленную версию. Спасибо за помощь ^)
