### ISSUE TITLE
проблема с ориентацией картинки и замена её

### ISSUE THREAD

**Issue by Kleri0N** [Koder-Teh/Boombox-Controller#7]
Когда скачал мод картинка была не взади бумбокса как на картинке с руководством а в самом бумбоксе с неправильной ориентацией, решил заменить файл, ничего не вышло, картинка просто пропала, а новая не появилась, размер картинки был 1000 х 562 формат Jpg

**Comment by Koder-Teh** [comment]
Привет, скинь мне логи BepInEx. Так же скинь картинку которую ты ставишь.

**Comment by Kleri0N** [comment]
[LogOutput.log](https://github.com/Koder-Teh/Boombox-Controller/files/13889781/LogOutput.log)
![MmaWIXdkYgI](https://github.com/Koder-Teh/Boombox-Controller/assets/155469615/914f9122-8f00-444f-977a-f81c0b978260)
Надеюсь это логи, я просто не знаю что это вот скрин на всякий из файла
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/155469615/e7f95c41-1fb9-472e-816b-f36da2b0121f)

**Comment by Koder-Teh** [comment]
Привет! Я поставил фотку на заднюю сторону бумбокса, и вроде как все нормально показывает и отображается. Вот скрин:
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/82925518/f3067c12-9e3d-47a0-90b7-563001b61045)
Я помню мне писал один иностранец, о такой проблеме. Но как я понял, надо было просто переустановить мод. Ну как минимум иностранцу помогло.
