### ISSUE TITLE
config not generating in configs folder

### ISSUE THREAD

**Issue by broilerosu** [Koder-Teh/Boombox-Controller#8]
no ability to use config with r2modman client or thunderstore app 

can you also impliment a feature to play boombox while not holding it in ur hotbar slot but still uses battery

**Comment by Koder-Teh** [comment]
> no ability to use config with r2modman client or thunderstore app
> 
> can you also impliment a feature to play boombox while not holding it in ur hotbar slot but still uses battery

Привет! Насчет поддержки мод менеджера r2modman, я еще подумаю. Но вторую просьбу твою я выполнил. Спасибо что пользуешься моим модом :)
