### ISSUE TITLE
another issue is incompatibility with HolographicWings LethalExpansion mod 

### ISSUE THREAD

**Issue by broilerosu** [Koder-Teh/Boombox-Controller#9]
![image](https://github.com/Koder-Teh/Boombox-Controller/assets/47702237/b4ec9100-aeb2-4153-9f3d-bb9bb3303c13)

due to the chat messages the LethalExpansion mod is having a massive incompatibility issue causing crritical problems 

![image](https://github.com/Koder-Teh/Boombox-Controller/assets/47702237/06191237-8807-469f-9909-b4a0a96bb009)

**Comment by Koder-Teh** [comment]
> ![image](https://private-user-images.githubusercontent.com/47702237/293830040-b4ec9100-aeb2-4153-9f3d-bb9bb3303c13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzMzNjUsIm5iZiI6MTcwNDQzMzA2NSwicGF0aCI6Ii80NzcwMjIzNy8yOTM4MzAwNDAtYjRlYzkxMDAtYWViMi00MTUzLTlmM2QtYmI5YmIzMzAzYzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA1Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMWY5ZGZiYjE4MGNlMzJlNzkxYjkwZmQ4ZDcxNTZkM2UzYjNmODM0NDNmZjRkOGMxZWIzMWZhYzdhMWE4ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtHHbqlTV7K-knG0ej1hKqz973J96uBfGUiBIsFzmIY)
> 
> due to the chat messages the LethalExpansion mod is having a massive incompatibility issue causing crritical problems
> 
> ![image](https://private-user-images.githubusercontent.com/47702237/293830085-06191237-8807-469f-9909-b4a0a96bb009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzMzNjUsIm5iZiI6MTcwNDQzMzA2NSwicGF0aCI6Ii80NzcwMjIzNy8yOTM4MzAwODUtMDYxOTEyMzctODgwNy00NjlmLTk5MDktYjRhMGE5NmJiMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA1Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYTk4M2Q0NWVkZjI4MWMzNDk5ZGVkZmNiNTU1MTVhZTFlNTlkN2M4MzY1M2I3ZGVhYjM2NTBkZWIxMTQ1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3SXN7TjGN3yxLR285LR16GSdSLRpD4ipg8JxJy53t50)

Привет! Вопрос решен с данной модификацией. Спасибо что отписали о проблеме :)
